# KRM YAML for Terraform Blueprint Metadata
# Standard: https://docs.google.com/document/d/1uMhNixV5RsH3s21pniLZpQDkSLS2cABh2lo1fkq2hMY/edit
apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  # Machine-readable name.
  name: terraform-google-discovery-engine-app
  # Source repository details.
  source:
    type: git
    # Using a placeholder URL as the source repository is not provided.
    repo: https://github.com/GoogleCloudPlatform/terraform-google-discovery-engine-app
  # Current release version.
  version: 1.0.0
  # Actuation tool details.
  actuationTool:
    type: Terraform
    # Derived from the `required_version` block in the Terraform code.
    versions:
      - ">= 1.3"
  # Human-readable title.
  title: Vertex AI Search and Conversation App
  # Descriptions.
  description:
    # A brief, one-sentence description.
    tagline: Deploys a Vertex AI Search or Conversation App (Discovery Engine) with associated data stores.
    # A more detailed explanation of the blueprint's purpose.
    detailed: This module creates a Google Cloud Vertex AI Search and Conversation App (formerly Discovery Engine). It supports both SEARCH and CHAT solution types, configures data stores, and handles API enablement.
  # List of examples for using the blueprint.
  examples:
    - name: simple_search_app
      location: examples/simple_search_app
      title: Simple Search App
      description: A basic example of a SEARCH solution type app with a default data store.
  # Links to official documentation.
  documentations:
    - title: Vertex AI Search and Conversation
      url: https://cloud.google.com/vertex-ai-search-and-conversation
spec:
  # Defines prerequisites for deploying the blueprint.
  requirements:
    # GCP APIs that need to be enabled.
    services:
      - discoveryengine.googleapis.com
      - serviceusage.googleapis.com
    # GCP IAM roles required to deploy the blueprint.
    roles:
      - level: Project
        roles:
          - roles/discovery.admin
          - roles/serviceusage.serviceUsageAdmin
  # Enables rich customization through UIs or CLIs.
  interfaces:
    # Lists input variables for the blueprint.
    variables:
      - name: project_id
        description: The project ID to deploy the Discovery Engine resources in.
        type: string
        required: true
      - name: location
        description: The location for the Discovery Engine App and Data Stores. Can be global, multi-regional (e.g., 'eu', 'us'), or regional. Note - Data Stores for an app must be in the same location.
        type: string
        required: true
      - name: display_name
        description: The base display name for the Discovery Engine App.
        type: string
        default: "discovery-engine-app"
        required: false
      - name: solution_type
        description: The solution type for the engine. Can be 'SOLUTION_TYPE_SEARCH' or 'SOLUTION_TYPE_CHAT'.
        type: string
        default: "SOLUTION_TYPE_SEARCH"
        required: false
      - name: industry_vertical
        description: The industry vertical for the data stores.
        type: string
        default: "GENERIC"
        required: false
      - name: collection_id
        description: The collection ID. For now, only 'default_collection' is supported.
        type: string
        default: "default_collection"
        required: false
      - name: data_stores
        description: A map of data stores to create and connect to the engine. The key is the 'data_store_id'. Each value is an object with a 'display_name' and an optional 'content_config' (defaults to 'NO_SCHEMA'). Note Data must be imported into the data store after creation.
        type: object
        required: false
        default:
          default-data-store:
            display_name: Default Data Store
            content_config: NO_SCHEMA
      - name: search_tier
        description: The search tier for a SEARCH solution. Can be 'SEARCH_TIER_STANDARD' or 'SEARCH_TIER_ENTERPRISE'.
        type: string
        default: "SEARCH_TIER_STANDARD"
        required: false
      - name: search_add_ons
        description: A list of search add-ons for a SEARCH solution. e.g., ['SEARCH_ADD_ON_LLM']
        type: list(string)
        default: []
        required: false
      - name: chat_app_language_code
        description: The default language code to use for the CHAT solution's agent (e.g., 'en'). Required if solution_type is 'SOLUTION_TYPE_CHAT'.
        type: string
        default: null
        required: false
      - name: chat_app_time_zone
        description: The timezone of the CHAT solution's agent (e.g., 'America/Los_Angeles'). Required for 'SOLUTION_TYPE_CHAT'.
        type: string
        default: "America/Los_Angeles"
        required: false
      - name: chat_app_business
        description: The display name for the business in the CHAT solution's agent. This is used in agent responses.
        type: string
        default: ""
        required: false
      - name: enable_apis
        description: A boolean to control the automatic enabling of the 'discoveryengine.googleapis.com' API.
        type: bool
        default: true
        required: false
    # Groups of related variables for better UI presentation.
    variableGroups:
      - name: "General Settings"
        description: "Core project and location settings."
        variables:
          - project_id
          - location
          - enable_apis
      - name: "Engine Configuration"
        description: "Configure the main Discovery Engine App."
        variables:
          - display_name
          - solution_type
          - industry_vertical
      - name: "Data Store Configuration"
        description: "Define the data stores to be connected to the engine."
        variables:
          - collection_id
          - data_stores
      - name: "Search Solution Settings"
        description: "Settings specific to the SEARCH solution type."
        variables:
          - search_tier
          - search_add_ons
      - name: "Chat Solution Settings"
        description: "Settings specific to the CHAT solution type."
        variables:
          - chat_app_language_code
          - chat_app_time_zone
          - chat_app_business
    # Lists the outputs of the blueprint.
    outputs:
      - name: engine
        description: The full Discovery Engine App resource object.
      - name: engine_id
        description: The unique ID of the Discovery Engine App.
      - name: engine_name
        description: The resource name of the created Discovery Engine App.
      - name: data_stores
        description: A map of the created Discovery Engine Data Store resource objects, keyed by the logical name provided in the input variable.
      - name: data_store_names
        description: A map of the created Data Store resource names, keyed by the logical name provided in the input variable.
